language: cpp

before_install:
  - echo Language
  - echo $LANG
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

install: make get-deps

compiler: gcc

notifications:
  email: false

branches:
  only:
    - master


